name: Metrics
on:
  schedule: [{cron: "0 0 * * 0"}]  # 매주 일요일 자동 실행
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: woozizi
          base: header, activity
          config_timezone: Asia/Seoul

          repositories_affiliations: owner, collaborator, contributor

          plugin_contributions: yes
          plugin_contributions_sections: repositories
          plugin_contributions_limit: 5

          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_limit: 8
